Repository equilibria-xyz/perennial-v2, pull requests merged in 2023-10, with the labels that each got.

#95 De-duplicate context loading in Vault
  packages/perennial-vault/contracts/Vault.sol
  packages/perennial-vault/contracts/interfaces/IVault.sol
  packages/perennial-vault/contracts/lib/StrategyLib.sol
  packages/perennial-vault/test/integration/vault/Vault.test.ts
Labels: protocol change

#122 add maker side to trigger orders
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/contracts/types/TriggerOrder.sol
  packages/perennial-extensions/test/helpers/invoke.ts
  packages/perennial-extensions/test/helpers/types.ts
  packages/perennial-extensions/test/integration/core/Orders.test.ts
  packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts
  yarn.lock
Labels: protocol change

#123 Relax invariant
  packages/perennial/contracts/Market.sol
  packages/perennial/test/unit/market/Market.test.ts
Labels: protocol change

#105 Merge commit / commitRequest in PythOracle
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/test/integration/core/Pyth.test.ts
  packages/perennial-oracle/contracts/interfaces/IPythOracle.sol
  packages/perennial-oracle/contracts/pyth/PythOracle.sol
  packages/perennial-oracle/test/integration/pyth/PythOracle.test.ts
  packages/perennial-oracle/test/unit/pyth/PythOracle.test.ts
Labels: protocol change

#125 Trigger order test cleanup
  packages/perennial-extensions/test/helpers/invoke.ts
  packages/perennial-extensions/test/helpers/types.ts
  packages/perennial-extensions/test/integration/core/Invoke.test.ts
  packages/perennial-extensions/test/integration/core/Orders.test.ts
  packages/perennial-extensions/test/integration/helpers/setupHelpers.ts
  packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts
Labels: testing

#129 Wrap charge fee
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/contracts/interfaces/IMultiInvoker.sol
  packages/perennial-extensions/test/helpers/invoke.ts
  packages/perennial-extensions/test/integration/core/Invoke.test.ts
  packages/perennial-extensions/test/integration/core/Orders.test.ts
  packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts
Labels: protocol change

#126 Pyth soft revert burn
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/test/integration/core/Liquidate.test.ts
  packages/perennial-extensions/test/integration/core/Pyth.test.ts
Labels: bug, protocol change

#124 Add closable magic value
  packages/perennial/contracts/Market.sol
  packages/perennial/contracts/interfaces/IMarket.sol
  packages/perennial/contracts/types/Order.sol
  packages/perennial/contracts/types/Position.sol
  packages/perennial/test/unit/market/Market.test.ts
  packages/perennial/test/unit/types/Order.test.ts
Labels: protocol change

#131 Enable Pyth batch price commits
  packages/perennial-deploy/deploy/003_deploy_oracle.ts
  packages/perennial-deploy/hardhat.config.ts
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/test/integration/core/Pyth.test.ts
  packages/perennial-oracle/contracts/interfaces/IPythFactory.sol
  packages/perennial-oracle/contracts/interfaces/IPythOracle.sol
  packages/perennial-oracle/contracts/pyth/PythFactory.sol
  packages/perennial-oracle/contracts/pyth/PythFactory_Arbitrum.sol
  packages/perennial-oracle/contracts/pyth/PythFactory_Optimism.sol
  packages/perennial-oracle/contracts/pyth/PythOracle.sol
  packages/perennial-oracle/test/integration/oracle/OracleFactory.test.ts
  packages/perennial-oracle/test/integration/pyth/PythOracle.test.ts
  packages/perennial-oracle/test/unit/pyth/PythOracle.test.ts
  packages/perennial/contracts/interfaces/IOracleProvider.sol
Labels: protocol change

#128 Soft revert liq + exec order
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/contracts/interfaces/IMultiInvoker.sol
  packages/perennial-extensions/test/helpers/invoke.ts
  packages/perennial-extensions/test/integration/core/Liquidate.test.ts
  packages/perennial-extensions/test/integration/core/Orders.test.ts
Labels: protocol change

#135 [v2.1] Add collateral withdrawal orders
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/contracts/types/TriggerOrder.sol
  packages/perennial-extensions/test/helpers/types.ts
  packages/perennial-extensions/test/integration/core/Invoke.test.ts
  packages/perennial-extensions/test/integration/core/Orders.test.ts
  packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts
Labels: protocol change

#130 Charge fee on update
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/contracts/interfaces/IMultiInvoker.sol
  packages/perennial-extensions/test/helpers/invoke.ts
  packages/perennial-extensions/test/integration/core/Invoke.test.ts
  packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts
Labels: protocol change

#138 Magic "close all" trigger orders
  packages/perennial-extensions/contracts/types/TriggerOrder.sol
  packages/perennial-extensions/test/integration/core/Orders.test.ts
Labels: protocol change

#139 OracleFactory wraps USDC on initialization
  packages/perennial-extensions/test/integration/helpers/setupHelpers.ts
  packages/perennial-oracle/contracts/OracleFactory.sol
  packages/perennial-oracle/contracts/interfaces/IOracleFactory.sol
  packages/perennial-oracle/test/integration/oracle/OracleFactory.test.ts
  packages/perennial-oracle/test/integration/pyth/PythOracle.test.ts
  packages/perennial-oracle/test/unit/oracle/OracleFactory.test.ts
  packages/perennial-oracle/test/unit/pyth/PythOracle.test.ts
  packages/perennial/test/integration/helpers/setupHelpers.ts
Labels: protocol change

#134 Oracle settlement callback
  packages/perennial-oracle/contracts/Oracle.sol
  packages/perennial-oracle/contracts/interfaces/IPythFactory.sol
  packages/perennial-oracle/contracts/interfaces/IPythOracle.sol
  packages/perennial-oracle/contracts/pyth/PythFactory.sol
  packages/perennial-oracle/contracts/pyth/PythOracle.sol
  packages/perennial-oracle/hardhat.config.ts
  packages/perennial-oracle/test/integration/pyth/PythOracle.test.ts
  packages/perennial-oracle/test/unit/oracle/Oracle.test.ts
  packages/perennial-oracle/test/unit/pyth/PythOracle.test.ts
  packages/perennial/contracts/Market.sol
  packages/perennial/contracts/interfaces/IOracleProvider.sol
Labels: protocol change

#141 [v2.1] Trigger Order interface fee
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/contracts/interfaces/IMultiInvoker.sol
  packages/perennial-extensions/contracts/types/InterfaceFee.sol
  packages/perennial-extensions/contracts/types/TriggerOrder.sol
  packages/perennial-extensions/test/helpers/invoke.ts
  packages/perennial-extensions/test/helpers/types.ts
  packages/perennial-extensions/test/integration/core/Orders.test.ts
  packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts
Labels: protocol change

#142 [v2.1][Fix] Fix Collateral withdraw orders
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/contracts/types/TriggerOrder.sol
  packages/perennial-extensions/test/integration/core/Orders.test.ts
Labels: protocol change

#144 Merge root v2.1 - Update Kept modifier, use onlyFactory modifier
  package.json
  packages/perennial-extensions/contracts/MultiInvoker.sol
  packages/perennial-extensions/contracts/interfaces/IMultiInvoker.sol
  packages/perennial-extensions/test/integration/core/Pyth.test.ts
  packages/perennial-extensions/test/integration/helpers/setupHelpers.ts
  packages/perennial-extensions/test/unit/MultiInvoker/MultiInvoker.test.ts
  packages/perennial-oracle/contracts/Oracle.sol
  packages/perennial-oracle/contracts/interfaces/IKeeperFactory.sol
  packages/perennial-oracle/contracts/interfaces/IOracle.sol
  packages/perennial-oracle/contracts/keeper/KeeperFactory.sol
  packages/perennial-oracle/contracts/keeper/KeeperOracle.sol
  packages/perennial-oracle/contracts/pyth/PythFactory.sol
  packages/perennial-oracle/contracts/pyth/PythFactory_Arbitrum.sol
  packages/perennial-oracle/contracts/pyth/PythFactory_Optimism.sol
  packages/perennial-oracle/test/integration/oracle/OracleFactory.test.ts
  packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts
  packages/perennial-oracle/test/unit/oracle/Oracle.test.ts
  packages/perennial-oracle/test/unit/pyth/PythOracleFactory.test.ts
  yarn.lock
Labels: protocol change

#140 [v2.1] Static Skew
  packages/perennial-deploy/deploy/004_deploy_market.ts
  packages/perennial-deploy/test/verification/arbitrum/perennial/verifyMarkets.test.ts
  packages/perennial-extensions/test/integration/core/Invoke.test.ts
  packages/perennial-extensions/test/integration/helpers/setupHelpers.ts
  packages/perennial-oracle/test/integration/pyth/PythOracleFactory.test.ts
  packages/perennial-vault/contracts/Vault.sol
  packages/perennial-vault/test/integration/helpers/setupHelpers.ts
  packages/perennial-vault/test/integration/vault/Vault.test.ts
  packages/perennial/contracts/Market.sol
  packages/perennial/contracts/test/PositionTester.sol
  packages/perennial/contracts/types/Local.sol
  packages/perennial/contracts/types/Order.sol
  packages/perennial/contracts/types/Position.sol
  packages/perennial/contracts/types/RiskParameter.sol
  packages/perennial/contracts/types/Version.sol
  packages/perennial/test/integration/core/fees.test.ts
  packages/perennial/test/integration/core/happyPath.test.ts
  packages/perennial/test/integration/core/liquidate.test.ts
  packages/perennial/test/integration/helpers/setupHelpers.ts
  packages/perennial/test/unit/market/Market.test.ts
  packages/perennial/test/unit/types/Position.test.ts
  packages/perennial/test/unit/types/RiskParameter.test.ts
Labels: protocol change
